theme = 'ananke'
defaultContentLanguage = 'he'
baseURL = 'https://wiseplate.blog/'
title = 'מדע בתנועה'

[params]
  mainSections = ['food','compare','run']
  favicon = "/images/favicon.png"
  custom_css = ['custom.css']
  post_content_classes= "sans-serif"
  description = "יתרונות וחסרונות תזונתיים של מזונות שונים - מידע מבוסס מחקר מדעי לתזונה בריאה"
  description_en = "Nutritional pros and cons of various foods - Scientifically-based information for a healthy diet."
  keywords = ["תזונה", "בריאות", "ערכים תזונתיים", "יתרונות בריאותיים", "מזון בריא", "דיאטה", "פירות", "ירקות", "חלבון", "ויטמינים"]
  keywords_en = ["Nutrition", "Health", "Nutritional Values", "Health Benefits", "Healthy Food", "Diet", "Fruits", "Vegetables", "Protein", "Vitamins"]
  [params.ananke]
    show_recent_posts = true

  [markup]
    [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe = true
      [markup.goldmark.parser]
        [markup.goldmark.parser.attribute]
          block = true
          title = true

[languages]
  [languages.he]
    languageCode = 'he'
    languageDirection = 'rtl'
    languageName = 'עברית'
    weight = 1

[[menu.main]]
  name = "אוכל"
  url = "/food/"
  weight = 10
[[menu.main]]
  name = "מה עדיף?"
  url = "/compare/"
  weight = 20
[[menu.main]]
  name = "ריצה"
  url = "/run/"
  weight = 30